### ISSUE TITLE
Twitch displaying purple logo on occasions

### ISSUE THREAD

**Issue by Bourne-ID** [Mahsaap/BluBotCore#3]
Occasionally when a caster goes live the purple screen (https://pbs.twimg.com/media/Dhx6eCVU8AALelo.jpg) is shown. Suspected caching issue with Twitch imaging servers, therefore add reasonable image checks to see if the image is purple, and if so delay call until it's not or until a timeout is reached. 

LiveMonitor.cs:373

**Comment by Mahsaap** [comment]
#4 pr
