### ISSUE TITLE
Incorrect time format

### ISSUE THREAD

**Issue by Bourne-ID** [Mahsaap/BluBotCore#8]
https://github.com/Mahsaap/BluBotCore/blob/4ac0f8c568e02d49942c971fa661add3425f3814/BluBotCore/Services/LiveMonitor.cs#L150

Time format is incorrect - MM is month, not minute (mm)

**Comment by Mahsaap** [comment]
I need to change that anyway. Because if placements. It's not always correct. This happens more at the starting of the bot. But still I need to fix that so its only 1 variable for time that will change.
